# Generated by Django 5.2.8 on 2025-11-23 13:39

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('courses', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='course',
            name='created_by',
            field=models.ForeignKey(help_text='Instructor who created this course', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='created_courses', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='professionalcertification',
            name='certification_type',
            field=models.CharField(choices=[('professional', 'Professional Certificate'), ('specialization', 'Specialization')], default='professional', help_text='Type of certification', max_length=20),
        ),
        migrations.AddField(
            model_name='professionalcertification',
            name='created_by',
            field=models.ForeignKey(help_text='Instructor who created this certification', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='created_certifications', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='user',
            name='bio',
            field=models.TextField(blank=True, help_text='Brief biography or description'),
        ),
        migrations.AddField(
            model_name='user',
            name='role',
            field=models.CharField(choices=[('learner', 'Learner'), ('instructor', 'Instructor')], default='learner', help_text='User role: Instructor can create courses, Learner can only take courses', max_length=20),
        ),
        migrations.AlterField(
            model_name='course',
            name='certification',
            field=models.ForeignKey(blank=True, help_text='Parent certification (optional - can be standalone course)', null=True, on_delete=django.db.models.deletion.CASCADE, related_name='courses', to='courses.professionalcertification'),
        ),
        migrations.CreateModel(
            name='CertificationEnrollment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('enrolled_at', models.DateTimeField(auto_now_add=True)),
                ('is_active', models.BooleanField(default=True)),
                ('certification', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='enrollments', to='courses.professionalcertification')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='certification_enrollments', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'db_table': 'certification_enrollments',
                'ordering': ['-enrolled_at'],
                'unique_together': {('user', 'certification')},
            },
        ),
    ]
